import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

// Email routing configuration
// All form submissions are routed to support@syntrarefining.com
const SUPPORT_EMAIL = "support@syntrarefining.com";

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const { formType, referenceId, formData } = await req.json();

    // Route all emails to support@syntrarefining.com
    // Test mode: Use verified test email for Resend sandbox mode
    // Once domain is verified, remove this override
    const toEmail = "eslam.embaby4@gmail.com";

    // Format email subject and body
    const formTypeDisplay = formType.replace(/_/g, ' ').toUpperCase();
    const subject = `[SYNTRA] ${formTypeDisplay} - ${referenceId}`;
    
    let body = `NEW FORM SUBMISSION RECEIVED\n`;
    body += `${'='.repeat(60)}\n\n`;
    body += `Reference ID: ${referenceId}\n`;
    body += `Form Type: ${formTypeDisplay}\n`;
    body += `Submitted: ${new Date().toLocaleString('en-US', { timeZone: 'America/Halifax' })} AST\n`;
    body += `Routed to: ${SUPPORT_EMAIL}\n\n`;
    body += `${'='.repeat(60)}\n`;
    body += `SUBMISSION DETAILS\n`;
    body += `${'='.repeat(60)}\n\n`;
    
    // Add form fields
    for (const [key, value] of Object.entries(formData)) {
      if (value && key !== 'form_type' && key !== 'additional_data') {
        const fieldName = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());

        // Format value based on type
        if (typeof value === 'object') {
          body += `${fieldName}: ${JSON.stringify(value, null, 2)}\n`;
        } else {
          body += `${fieldName}: ${value}\n`;
        }
      }
    }

    // Add additional data fields separately with better formatting
    if (formData.additional_data && Object.keys(formData.additional_data).length > 0) {
      body += `\n${'='.repeat(60)}\n`;
      body += `ADDITIONAL INFORMATION\n`;
      body += `${'='.repeat(60)}\n\n`;
      for (const [key, value] of Object.entries(formData.additional_data)) {
        if (value && value !== null && value !== '') {
          const fieldName = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());

          // Format value based on type
          let formattedValue = value;
          if (typeof value === 'boolean') {
            formattedValue = value ? 'Yes' : 'No';
          } else if (typeof value === 'object') {
            formattedValue = JSON.stringify(value, null, 2);
          }

          body += `${fieldName}: ${formattedValue}\n`;
        }
      }
    }

    body += `\n${'='.repeat(60)}\n`;
    body += `ADMIN ACTIONS\n`;
    body += `${'='.repeat(60)}\n\n`;
    body += `View in admin dashboard:\n`;
    body += `${req.headers.get('origin') || 'https://syntrarefining.com'}/admin.html\n\n`;
    body += `This email was automatically generated by the Syntra Forms system.\n`;

    const resendApiKey = Deno.env.get('RESEND_API_KEY');

    if (!resendApiKey) {
      console.error('RESEND_API_KEY not configured');
      return new Response(
        JSON.stringify({
          success: false,
          error: 'Email service not configured'
        }),
        {
          status: 500,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    const emailResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Syntra Refining Forms <onboarding@resend.dev>',
        to: [toEmail],
        subject: subject,
        text: body,
      }),
    });

    const emailResult = await emailResponse.json();

    if (!emailResponse.ok) {
      console.error('Failed to send email:', emailResult);
      return new Response(
        JSON.stringify({
          success: false,
          error: 'Failed to send email notification',
          details: emailResult
        }),
        {
          status: 500,
          headers: {
            ...corsHeaders,
            "Content-Type": "application/json",
          },
        }
      );
    }

    console.log('Email sent successfully:', emailResult);

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Email sent successfully',
        destinationEmail: toEmail,
        emailId: emailResult.id
      }),
      {
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  } catch (error) {
    console.error('Error processing notification:', error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  }
});